spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/tool/jpashop
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: trace
  org.hibernate.type: trace
